title: Riton64
author: riton64
email: augeh@cegetel.net
description: > # this means to ignore newlines until next key word
  gavin jerman's website for his software development projects, running exploits, and love of real ale
url: https://riton64/riton64.github.io
baseurl: /
markdown: kramdown
permalink: /:year/:month/:title/
lang: "en"
excerpt_separator: "\n\n\n" # 2 blank lines
date_format: "%B %d, %Y"
paginate: 10
paginate_path: /page/:num/
analytics: false            # include analytics

# Kramdown
kramdown:
  auto_ids: false           # don't auto generate ids from headings

# Layout
sidebar: true               # show a sidebar instead of the usual header
show_excerpts: true         # show article excerpts on the home page
show_related: true          # show the previous and next links after every post
show_description: false     # show the site description in the sidebar
show_title: true            # always keep the site title visible

# Styling
dark_header: true           # always keep the header dark
minimal: false              # use simpler style

# Menu
navigation:
  - {file: "index.html", icon: home}
  - {file: "projects.md", icon: clipboard}
  - {file: "search.md", icon: search}
  - {file: "archive.html", icon: archive}
  - {file: "about.md", icon: address-card}

external:                   # see http://fontawesome.com/icons
#  - {title: Mail, icon: envelope, url: "mailto:gavinjerman@github.com"}
  - {title: Github, icon: github, url: "https://github.com/jermware/jermware.github.io"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/gavinjerman"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
  #disqus_shortname: ""      # see https://disqus.com/
  #isso_domain: ""           # see https://posativ.org/isso/

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
